### ISSUE TITLE
Hana - No Sh1mmer Menu

### ISSUE THREAD

**Issue by Svansig** [CoolElectronics/sh1mmer.me#12]
After following the instructions on the site, I am unable to get a Hana machine to get to the Sh1mmer menu.

I have tried the following:
- Windows machine for host, web wax, chrome recovery extension
- Linux host, github instructions, dd to flash usb
- Three separate USB drives
- Three separate Hana devices

The machine starts from the usb, says it copies everything over, and then will just have a blank screen with a line about an image file, but with a missing leading "I" character (mage:file=/usr/share/sh1mmer-assets/Disclaimer.png;scale=1).  The only response I get out of it is that it will list more image file names if i hit the down arrow.  The enter key will either claim that there is no file or it will reboot the machine entirely.

**Comment by Svansig** [comment]
I was able to use the tool by following the options available in the script, but it seems like it will not show images

**Comment by velzie** [comment]
This is a known fault for hana (and coral?)
The raw shim for this board we have was compiled so long ago that support for graphics in tty hadn't been added in, so porting BW to it is impossible.

If you switch to the legacy branch you should be able to build a sh1mmer image from before the switch to frecon graphics for the menu

As a temporary workaround you can press the down arrow once, hit enter, down arrow again and enter. All functions remain usable despite the lack of gui

A warning should be pushed to the website for it probably

**Comment by CoolElectronics** [comment]
This is a known fault for hana (and coral?)
The raw shim for this board we have was compiled so long ago that support for graphics in tty hadn't been added in, so porting BW to it is impossible.

If you switch to the legacy branch you should be able to build a sh1mmer image from before the switch to frecon graphics for the menu

As a temporary workaround you can press the down arrow once, hit enter, down arrow again and enter. All functions remain usable despite the lack of gui

A warning should be pushed to the website for it probably

**Comment by Svansig** [comment]
Hey, glad to see the workaround I used is the blessed path, lol.  This tool is incredible though, thank you so much for your efforts.

**Comment by MadjikDotPng** [comment]
I'm having a similar problem, except on coral. Whenever loading in it displays the usual copying USB screen, then it just goes black. Down + Enter x2 just displays "bash: : No such file or directory" and I honestly do not know what to do.

**Comment by spacepeanut1** [comment]
I can figure it out ether gan you just say what to press to unenroll

**Comment by velzie** [comment]
instructions on how to build a legacy shim have been added. fairly soon we'll have a legacy web builder and we can close this.

**Comment by spacepeanut1** [comment]
i know your probblay a very busy but how long untell the legicy wed builder is up because I want to know if it will be worth it to build my own file

**Comment by spacepeanut1** [comment]
how is it possible the when I plug in the simmer wax and tries to flash the USB opens up I'm so confused

**Comment by TheMemeSniper** [comment]
literally what are you asking

**Comment by TheMemeSniper** [comment]
# literally what are you asking

**Comment by amelia-bartlett** [comment]
> how is it possible the when I plug in the simmer wax and tries to flash the USB opens up I'm so confused

I don't think anyone will be able to help you, since even your question is confusing.
You should rephrase (hint: adding more detail on what you tried etc will help make your issue clearer) since it seems like you shuffled your word order somehow.  You should also consider opening a new issue once you figure out how to form a coherent sentence, unless you are sure that your issue is an extension of this one.

What your issue currently sounds like is (although there are many possible interpretations):
1)You are not sure how to do something ("how is it possible")
2)The issue occurs when you connect a device, presumably a USB you have attempted to flash sh1mmer to ("when I plug in the simmer")[sic]
3)Something happens with wax ("wax")
4)There is a secondary problem as well ("and")
5)I can see multiple ways of interpreting the next section:

5a1)The secondary problem is triggered when you try to flash your USB with the image ("tries to flash the USB")
5a2)Your file manager auto opens, and the device auto mounts ("the USB opens up")

5b1)The secondary problem is that something tries to overwrite data on your USB, but you don't want it to ("tries to flash the USB")
5b2)Whatever it is is a process that starts on your computer, without interaction from you ("opens up")

5c1)The secondary problem is triggered when you try to flash something - likely a USB mass storage device - with the image ("tries to flash")
5c2)Your USB devices casing physically opens ("the USB opens up")

Also, while you are rewriting your question, consider using commas and other forms of punctuation to avoid ambiguity.

**Comment by ProgrammerIn-wonderland** [comment]
Currently compiling a special version of sh1mmer for pre-frecon boards

**Comment by ProgrammerIn-wonderland** [comment]
> instructions on how to build a legacy shim have been added. fairly soon we'll have a legacy web builder and we can close this.

working on it

**Comment by ProgrammerIn-wonderland** [comment]
![Screenshot_20230217_160414](https://user-images.githubusercontent.com/30693865/219620643-93a3beb8-0fec-4d18-aa3d-93b2c7883eac.png)
this is gonna take an hour or two but I'll have it live on https://sh1mmer.me/buildlegacy

**Comment by amelia-bartlett** [comment]
> ![Screenshot_20230217_160414](https://user-images.githubusercontent.com/30693865/219620643-93a3beb8-0fec-4d18-aa3d-93b2c7883eac.png) this is gonna take an hour or two but I'll have it live on https://sh1mmer.me/buildlegacy

sounds cool!

**Comment by ProgrammerIn-wonderland** [comment]
cool, did it
https://sh1mmer.me/buildlegacy
